version: "3.8"
services:
  web:
    build: .
    image: sneeyalionessdk/workshop:12.0.10
    ports:
      - "9999:9999"
  mongo:
    image: mongo:4.2.8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=mydb
# docker-compose build // Build image
# docker-compose up // Foreground process
# docker-compose up -d // Background process
# docker-compose ps // List of containers
# docker-compose logs web // View log of web service
# docker-compose down // Remove all resources (container, network, volume)

# 1. Fork
# 2. Create file docker-compose.yml
# 3. PR
# 4. Push to Docker Hub